---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edu-api-role
rules:
  - apiGroups:
      - "capsule.clastix.io"
    resources:
      - "tenants"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edu-api
subjects:
  - kind: ServiceAccount
    namespace: default
    name: api-sa
roleRef:
  kind: ClusterRole
  name: edu-api-role
  apiGroup: rbac.authorization.k8s.io

